"""initial_schema

Revision ID: 389108adeb63
Revises: 
Create Date: 2025-12-20 18:19:30.677790
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '389108adeb63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('game_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('telegram_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('messages',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_player_recent', 'messages', ['player_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_table('player_keys',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('key_value', sa.Text(), nullable=False),
    sa.Column('access_limit', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('first_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_value')
    )
    op.create_table('player_trust',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'agent_id')
    )
    op.create_table('story_milestones',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.Text(), nullable=False),
    sa.Column('reached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'milestone_id')
    )
    op.create_table('key_access_log',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['player_keys.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_knowledge',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('source_agent', sa.Text(), nullable=True),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_player_category', 'player_knowledge', ['player_id', 'category'], unique=False, postgresql_using='btree')
    op.create_table('trust_events',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trust_events_player_recent', 'trust_events', ['player_id', 'created_at'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trust_events_player_recent', table_name='trust_events', postgresql_using='btree')
    op.drop_table('trust_events')
    op.drop_index('idx_knowledge_player_category', table_name='player_knowledge', postgresql_using='btree')
    op.drop_table('player_knowledge')
    op.drop_table('key_access_log')
    op.drop_table('story_milestones')
    op.drop_table('player_trust')
    op.drop_table('player_keys')
    op.drop_index('idx_messages_player_recent', table_name='messages', postgresql_using='btree')
    op.drop_table('messages')
    op.drop_table('players')
    # ### end Alembic commands ###
